# Generated by Django 5.0.1 on 2024-03-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_model', models.CharField(max_length=30)),
                ('car_brand', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('define', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='car_detail', to='car_wiki.car')),
            ],
        ),
    ]
