# Generated by Django 5.0.1 on 2024-03-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('CarID', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=30)),
                ('Define', models.CharField(max_length=30)),
                ('Brand', models.CharField(max_length=30)),
            ],
        ),
    ]
