# Generated by Django 5.0.1 on 2024-03-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_wiki', '0002_car_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('Car', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='car_detail', serialize=False, to='car_wiki.car')),
                ('Define', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Define',
            new_name='CarModel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='car',
            name='Type',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images')),
                ('CarDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_wiki.cardetail')),
            ],
        ),
    ]
