# Generated by Django 5.0.1 on 2024-03-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
