# Generated by Django 5.0.1 on 2024-03-04 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNo', models.IntegerField()),
                ('Picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('ReplyID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('ArticleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.article')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField()),
                ('Title', models.CharField(max_length=100)),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Transaction.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('IsBanned', models.BooleanField()),
                ('IsFinished', models.BooleanField()),
                ('IsAgreed', models.BooleanField()),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.product')),
                ('BuyerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='Transaction.user')),
                ('SellerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='Transaction.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.user'),
        ),
    ]
