# Generated by Django 5.0.1 on 2024-03-05 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='ArticleID',
        ),
        migrations.AlterField(
            model_name='order',
            name='SellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='account.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='BuyerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to='account.user'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SellerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='account.user'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
