# Generated by Django 5.0.1 on 2024-03-05 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0005_product_car'),
        ('car_wiki', '0003_cardetail_rename_define_car_carmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Location',
            field=models.TextField(default=datetime.datetime(2024, 3, 5, 12, 51, 10, 996875, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_wiki.car'),
        ),
    ]
